source 'https://github.com/RyuichiTanimoto/cocoapods-private-specs.git'
platform :ios, '8.0'

use_frameworks!

target 'FoundationUtilities_Example' do
  pod 'FoundationUtilities', :path => '../'

  target 'FoundationUtilities_Tests' do
    inherit! :search_paths
  end
end
